### ISSUE TITLE
st_cli service servicename doesnot work 

### ISSUE THREAD

**Issue by humayuntanwar** [Huzaifaahmed20/stacked_cli#1]
st_cli service servicename doesnot work  

generates the following to services file:
`
import './services\ThemeService.dart';
import './services\Services.dart';
import './services\ApiService.dart';
import './services\ApiClientService.dart';
import 'package:stacked_services/stacked_services.dart';

@module
abstract class Services {
  @lazySingleton
  NavigationService get navigationService;

  @lazySingleton
  DialogService get dialogService;

  @lazySingleton
  Services\ApiClientService get services\ApiClientService;
  @lazySingleton
  Services\ApiService get services\ApiService;
  @lazySingleton
  Services\Services get services\Services;
  @lazySingleton
  Services\ThemeService get services\ThemeService;
`

may be linked to the following https://github.com/dart-lang/build/issues/2803

**Comment by Huzaifaahmed20** [comment]
Removing the dependency override for the dart analyzer in Pubspec.yaml may solve the issue

**Comment by madhavam12** [comment]
Hi @Huzaifaahmed20 I'm facing the same error. How to resolve it? i did not quite understad how to remove the dependency override. Please help
